# Generated by Django 4.1 on 2022-10-10 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0120_customerkyc_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerkyc",
            name="status",
            field=models.ForeignKey(
                default=40,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customerKYC_status",
                to="LOAN.form_status",
            ),
        ),
    ]
