# Generated by Django 4.1 on 2022-10-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disbursement_customer_kyc",
            name="Disbursement_Payment_Mode",
        ),
    ]
