# Generated by Django 4.1 on 2022-10-12 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0002_remove_disbursement_customer_kyc_disbursement_payment_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disbursement_customer_kyc",
            name="Charfield5",
        ),
    ]
