# Generated by Django 4.1 on 2022-10-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0003_remove_disbursement_customer_kyc_charfield5"),
    ]

    operations = [
        migrations.AddField(
            model_name="disbursement_customer_kyc",
            name="Charfield5",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
