# Generated by Django 4.1 on 2022-10-12 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0004_disbursement_customer_kyc_charfield5"),
    ]

    operations = [
        migrations.AddField(
            model_name="disbursement_customer_kyc",
            name="Disbursement_Payment_Mode",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Disburse_Payment_Mode",
                to="LOAN.disbursementmode",
            ),
            preserve_default=False,
        ),
    ]
