# Generated by Django 4.1 on 2022-10-12 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0005_disbursement_customer_kyc_disbursement_payment_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="disbursement_customer_kyc",
            name="Disbursement_Date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
