# Generated by Django 4.1 on 2022-10-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0006_disbursement_customer_kyc_disbursement_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disbursement_customer_kyc",
            name="group_Loan_Agreement",
            field=models.FileField(upload_to="pdf"),
        ),
    ]
