# Generated by Django 4.1 on 2022-10-16 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0007_alter_disbursement_customer_kyc_group_loan_agreement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerkyc",
            name="District",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="state",
                to="LOAN.dist",
            ),
        ),
    ]
