# Generated by Django 4.1 on 2022-10-16 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0008_alter_customerkyc_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerkyc",
            name="District",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="District",
                to="LOAN.dist",
            ),
        ),
        migrations.AlterField(
            model_name="customerkyc",
            name="confirmDistrict",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="confirm_District",
                to="LOAN.dist",
            ),
        ),
    ]
