# Generated by Django 4.1 on 2022-10-20 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0009_alter_customerkyc_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disbursement_customer_kyc",
            name="status",
            field=models.ForeignKey(
                default=41,
                on_delete=django.db.models.deletion.PROTECT,
                to="LOAN.form_status",
            ),
        ),
    ]
