# Generated by Django 4.1 on 2022-10-20 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0010_alter_disbursement_customer_kyc_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="emiStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statusValue", models.CharField(max_length=100)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=100)),
                ("updated_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="loanEMI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installmentDate", models.DateField()),
                ("principleAmount", models.FloatField()),
                ("interestAmoun", models.FloatField()),
                ("installmentAmount", models.FloatField()),
                ("outstandingPrincipal", models.FloatField()),
                ("Doc2image", models.ImageField(null=True, upload_to="img")),
                ("Doc3image", models.ImageField(null=True, upload_to="img")),
                ("Doc4image", models.ImageField(null=True, upload_to="img")),
                ("Doc5image", models.ImageField(null=True, upload_to="img")),
                ("intfield1", models.IntegerField(null=True)),
                ("intfield2", models.IntegerField(null=True)),
                ("intfield3", models.IntegerField(null=True)),
                ("intfield4", models.IntegerField(null=True)),
                ("intfield5", models.IntegerField(null=True)),
                ("DateField1", models.DateTimeField(null=True)),
                ("DateField2", models.DateTimeField(null=True)),
                ("DateField3", models.DateTimeField(null=True)),
                ("DateField4", models.DateTimeField(null=True)),
                ("DateField5", models.DateTimeField(null=True)),
                ("Charfield1", models.CharField(max_length=50, null=True)),
                ("Charfield2", models.CharField(max_length=50, null=True)),
                ("Charfield3", models.CharField(max_length=50, null=True)),
                ("Charfield4", models.CharField(max_length=50, null=True)),
                ("Charfield5", models.CharField(max_length=50, null=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="LOAN.center"
                    ),
                ),
                (
                    "emiStatus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LOAN.emistatus"
                    ),
                ),
                (
                    "loanId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LOAN.loan_application_details",
                    ),
                ),
            ],
        ),
    ]
