# Generated by Django 4.1 on 2022-10-20 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0012_alter_loanemi_installmentdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanemi",
            name="emiStatus",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                to="LOAN.emistatus",
            ),
        ),
    ]
