# Generated by Django 4.1 on 2022-10-31 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0015_remove_disbursement_customer_kyc_loanemi"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanemi",
            name="disberseLoanID",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="LOAN.disbursement_customer_kyc",
            ),
            preserve_default=False,
        ),
    ]
