# Generated by Django 4.1 on 2022-11-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0016_loanemi_disberseloanid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanemi",
            name="disberseLoanID",
        ),
        migrations.AddField(
            model_name="disbursement_customer_kyc",
            name="customerEMI",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                to="LOAN.loanemi",
            ),
        ),
    ]
