# Generated by Django 4.1 on 2022-11-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0017_remove_loanemi_disberseloanid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disbursement_customer_kyc",
            name="customerEMI",
        ),
    ]
