# Generated by Django 4.1 on 2022-11-01 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0020_alter_disbursement_customer_kyc_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disbursement_customer_kyc",
            name="CustomerEMI",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="LOAN.loanemi",
            ),
        ),
        migrations.AlterField(
            model_name="disbursement_customer_kyc",
            name="status",
            field=models.ForeignKey(
                default=41,
                on_delete=django.db.models.deletion.PROTECT,
                to="LOAN.form_status",
            ),
        ),
    ]
