# Generated by Django 4.1 on 2022-11-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0024_alter_customerkyc_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerkyc",
            name="confirmDistrict",
            field=models.CharField(max_length=100),
        ),
    ]
