# Generated by Django 4.1 on 2022-11-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0025_alter_customerkyc_confirmdistrict"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disbursement_customer_kyc",
            name="Disbursement_Date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="disbursement_customer_kyc",
            name="Timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
