# Generated by Django 4.1 on 2022-11-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0026_alter_disbursement_customer_kyc_disbursement_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerkyc",
            name="updatedDate",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customerkyc",
            name="Timestamp",
            field=models.DateTimeField(),
        ),
    ]
