# Generated by Django 4.1 on 2022-11-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0028_approved_customer_kyc_updateddate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmiCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EmiNumber", models.IntegerField()),
                ("EmiNumberValue", models.CharField(max_length=50, null=True)),
                ("CreatedBy", models.CharField(max_length=50, null=True)),
                ("UpdatedBy", models.CharField(max_length=50, null=True)),
                ("CreatedDate", models.DateTimeField()),
                ("updatedDate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="loanemi",
            name="DateField1",
        ),
        migrations.AddField(
            model_name="loanemi",
            name="PaymentData",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
