# Generated by Django 4.1 on 2022-11-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0030_alter_loanemi_paymentdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmiPaymentMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EmiPaymentModeName", models.CharField(max_length=50, null=True)),
                ("CreatedBy", models.CharField(max_length=50, null=True)),
                ("UpdatedBy", models.CharField(max_length=50, null=True)),
                ("CreatedDate", models.DateTimeField()),
                ("updatedDate", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
