# Generated by Django 4.1 on 2022-11-19 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0031_emipaymentmode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loanemi",
            old_name="Charfield1",
            new_name="TransactionId",
        ),
    ]
