# Generated by Django 4.1 on 2022-11-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0032_rename_charfield1_loanemi_transactionid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanemi",
            name="TransactionId",
            field=models.IntegerField(null=True),
        ),
    ]
