# Generated by Django 4.1 on 2022-11-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0034_remove_loanemi_doc2image_loanemi_emisubmittedby"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanemi",
            name="intfield2",
        ),
        migrations.AddField(
            model_name="loanemi",
            name="EmiPaymentMode",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="LOAN.disbursementmode",
            ),
        ),
    ]
