# Generated by Django 4.1 on 2022-11-20 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("LOAN", "0036_rename_paymentdata_loanemi_paymentdate_audittable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanemi",
            name="emiSubmittedBy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
