# Generated by Django 4.1 on 2022-11-20 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("LOAN", "0037_alter_loanemi_emisubmittedby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audittable",
            name="emiReverseBy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
