# Generated by Django 4.1 on 2022-11-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0039_alter_audittable_emireverseby_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audittable",
            old_name="loanId",
            new_name="LoanId",
        ),
    ]
