# Generated by Django 4.1 on 2022-11-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0040_rename_loanid_audittable_loanid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audittable",
            name="TransactionId",
            field=models.IntegerField(null=True),
        ),
    ]
