# Generated by Django 4.1 on 2022-11-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0041_alter_audittable_transactionid"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankTransactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Doc3image", models.ImageField(null=True, upload_to="img")),
                ("Doc4image", models.ImageField(null=True, upload_to="img")),
                ("Doc5image", models.ImageField(null=True, upload_to="img")),
                ("intfield1", models.IntegerField(null=True)),
                ("intfield3", models.IntegerField(null=True)),
                ("intfield4", models.IntegerField(null=True)),
                ("intfield5", models.IntegerField(null=True)),
                ("DateField2", models.DateTimeField(null=True)),
                ("DateField3", models.DateTimeField(null=True)),
                ("DateField4", models.DateTimeField(null=True)),
                ("DateField5", models.DateTimeField(null=True)),
                ("Charfield2", models.CharField(max_length=50, null=True)),
                ("Charfield3", models.CharField(max_length=50, null=True)),
                ("Charfield4", models.CharField(max_length=50, null=True)),
                ("Charfield5", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
