# Generated by Django 4.1 on 2022-12-22 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("LOAN", "0043_transactionsmode_banktransactions_accountnumber_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashBookReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BranchDayCloseDate", models.DateField()),
                ("CashDate", models.DateField()),
                ("CashBalance", models.IntegerField()),
                ("_2000Note", models.IntegerField()),
                ("_500Note", models.IntegerField()),
                ("_200Note", models.IntegerField()),
                ("_100Note", models.IntegerField()),
                ("_50Note", models.IntegerField()),
                ("_20Note", models.IntegerField()),
                ("_10Note", models.IntegerField()),
                ("_5Note", models.IntegerField()),
                ("_2Note", models.IntegerField()),
                ("_1Note", models.IntegerField()),
                ("_10Coin", models.IntegerField()),
                ("_5Coin", models.IntegerField()),
                ("_2Coin", models.IntegerField()),
                ("_1Coin", models.IntegerField()),
                ("CreatedDate", models.DateTimeField()),
                ("updatedDate", models.DateTimeField(auto_now=True)),
                (
                    "Branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="LOAN.branch"
                    ),
                ),
                (
                    "BranchManager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
