# Generated by Django 4.1 on 2023-01-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0046_remove_cashbookreport_center_cashbookreport_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account_Transections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TrasID", models.IntegerField()),
                ("Credit", models.IntegerField()),
                ("Debit", models.IntegerField()),
                ("AccountBalance", models.IntegerField()),
                ("TransDate", models.DateTimeField(auto_now=True)),
                ("TransTimeStamp", models.DateTimeField(auto_now=True)),
                (
                    "Branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="LOAN.branch",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cashbookreport",
            name="TrasID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="LOAN.account_transections",
            ),
        ),
    ]
