# Generated by Django 4.1 on 2023-01-03 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0047_account_transections_cashbookreport_trasid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashbookreport",
            name="Branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="LOAN.branch"
            ),
        ),
    ]
