# Generated by Django 4.1 on 2023-01-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0049_cashbookreport__20coin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashbookreport",
            name="TrasID",
        ),
    ]
