# Generated by Django 4.1 on 2023-01-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0050_remove_cashbookreport_trasid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cashbookreport",
            old_name="Branch",
            new_name="Branch_Name",
        ),
    ]
