# Generated by Django 4.1 on 2023-01-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0051_rename_branch_cashbookreport_branch_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account_transections",
            name="Charfield2",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="account_transections",
            name="Charfield3",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="account_transections",
            name="Charfield4",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="account_transections",
            name="Charfield5",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="account_transections",
            name="DateField2",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="account_transections",
            name="DateField3",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="account_transections",
            name="DateField4",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="account_transections",
            name="DateField5",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="account_transections",
            name="Doc3image",
            field=models.ImageField(null=True, upload_to="img"),
        ),
        migrations.AddField(
            model_name="account_transections",
            name="Doc4image",
            field=models.ImageField(null=True, upload_to="img"),
        ),
        migrations.AddField(
            model_name="account_transections",
            name="Doc5image",
            field=models.ImageField(null=True, upload_to="img"),
        ),
        migrations.AddField(
            model_name="account_transections",
            name="intfield1",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="account_transections",
            name="intfield3",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="account_transections",
            name="intfield4",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="account_transections",
            name="intfield5",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cashbookreport",
            name="Charfield2",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cashbookreport",
            name="Charfield3",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cashbookreport",
            name="Charfield4",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cashbookreport",
            name="Charfield5",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cashbookreport",
            name="DateField2",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="cashbookreport",
            name="DateField3",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="cashbookreport",
            name="DateField4",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="cashbookreport",
            name="DateField5",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="cashbookreport",
            name="Doc3image",
            field=models.ImageField(null=True, upload_to="img"),
        ),
        migrations.AddField(
            model_name="cashbookreport",
            name="Doc4image",
            field=models.ImageField(null=True, upload_to="img"),
        ),
        migrations.AddField(
            model_name="cashbookreport",
            name="Doc5image",
            field=models.ImageField(null=True, upload_to="img"),
        ),
        migrations.AddField(
            model_name="cashbookreport",
            name="intfield1",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cashbookreport",
            name="intfield3",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cashbookreport",
            name="intfield4",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cashbookreport",
            name="intfield5",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="account_transections",
            name="TrasID",
            field=models.CharField(max_length=10000),
        ),
    ]
