# Generated by Django 4.1 on 2023-01-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0053_cashbookreport_transid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Account_Transections",
            new_name="Account_Transaction",
        ),
    ]
