# Generated by Django 4.1 on 2023-01-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0054_rename_account_transections_account_transaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cashbookreport",
            old_name="_100Note",
            new_name="Coin1",
        ),
        migrations.RenameField(
            model_name="cashbookreport",
            old_name="_10Coin",
            new_name="Coin10",
        ),
        migrations.RenameField(
            model_name="cashbookreport",
            old_name="_10Note",
            new_name="Coin2",
        ),
        migrations.RenameField(
            model_name="cashbookreport",
            old_name="_1Coin",
            new_name="Coin20",
        ),
        migrations.RenameField(
            model_name="cashbookreport",
            old_name="_1Note",
            new_name="Coin5",
        ),
        migrations.RenameField(
            model_name="cashbookreport",
            old_name="_2000Note",
            new_name="Note1",
        ),
        migrations.RenameField(
            model_name="cashbookreport",
            old_name="_200Note",
            new_name="Note10",
        ),
        migrations.RenameField(
            model_name="cashbookreport",
            old_name="_20Coin",
            new_name="Note100",
        ),
        migrations.RenameField(
            model_name="cashbookreport",
            old_name="_20Note",
            new_name="Note2",
        ),
        migrations.RenameField(
            model_name="cashbookreport",
            old_name="_2Coin",
            new_name="Note20",
        ),
        migrations.RenameField(
            model_name="cashbookreport",
            old_name="_2Note",
            new_name="Note200",
        ),
        migrations.RenameField(
            model_name="cashbookreport",
            old_name="_50Note",
            new_name="Note2000",
        ),
        migrations.RenameField(
            model_name="cashbookreport",
            old_name="_500Note",
            new_name="Note5",
        ),
        migrations.RenameField(
            model_name="cashbookreport",
            old_name="_5Coin",
            new_name="Note50",
        ),
        migrations.RenameField(
            model_name="cashbookreport",
            old_name="_5Note",
            new_name="Note500",
        ),
    ]
