# Generated by Django 4.1 on 2023-02-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0056_customerkyc_charfield10_customerkyc_charfield6_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerkyc",
            name="Custimage",
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
