# Generated by Django 4.1 on 2023-02-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0057_alter_customerkyc_custimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerkyc",
            name="Custimage",
            field=models.ImageField(upload_to="img"),
        ),
    ]
