# Generated by Django 4.1 on 2023-03-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0058_alter_customerkyc_custimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approved_customer_kyc",
            name="Aadhaar",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="disbursement_customer_kyc",
            name="Aadhaar",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="rejected_customer_kyc",
            name="Aadhaar",
            field=models.BigIntegerField(),
        ),
    ]
