# Generated by Django 4.1 on 2023-03-31 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("LOAN", "0059_alter_approved_customer_kyc_aadhaar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="userRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=100)),
                ("updated_date", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(max_length=100)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="auth.group"
                    ),
                ),
            ],
        ),
    ]
