# Generated by Django 4.1 on 2023-03-31 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("LOAN", "0060_userrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="Charfield1",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userrole",
            name="Charfield2",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userrole",
            name="Charfield3",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userrole",
            name="Charfield4",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userrole",
            name="Charfield5",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userrole",
            name="Charfield6",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userrole",
            name="Charfield7",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userrole",
            name="Charfield8",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userrole",
            name="Charfield9",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userrole",
            name="branchName",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="LOAN.branch"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userrole",
            name="userName",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
