# Generated by Django 4.1 on 2023-04-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0061_userrole_charfield1_userrole_charfield2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loandetails",
            name="Charfield1",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="Charfield10",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="Charfield2",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="Charfield3",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="Charfield4",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="Charfield5",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="Charfield6",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="Charfield7",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="Charfield8",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="Charfield9",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="DateField1",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="DateField2",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="DateField3",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="DateField4",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="DateField5",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="intfield1",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="intfield2",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="intfield3",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="intfield4",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="intfield5",
            field=models.IntegerField(null=True),
        ),
    ]
