# Generated by Django 4.1 on 2023-04-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0062_loandetails_charfield1_loandetails_charfield10_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loandetails",
            name="intfield1",
        ),
        migrations.RemoveField(
            model_name="loandetails",
            name="intfield2",
        ),
        migrations.AddField(
            model_name="loandetails",
            name="created_by",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="loanProcessingCharge",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="loanProcessingFee",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="updated_by",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="loandetails",
            name="updated_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
