# Generated by Django 4.1 on 2023-04-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0064_center_charfield1_center_charfield2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="center",
            name="Charfield1",
        ),
        migrations.RemoveField(
            model_name="center",
            name="Charfield2",
        ),
        migrations.RemoveField(
            model_name="center",
            name="Charfield3",
        ),
        migrations.RemoveField(
            model_name="center",
            name="Charfield4",
        ),
        migrations.RemoveField(
            model_name="center",
            name="Charfield5",
        ),
        migrations.RemoveField(
            model_name="center",
            name="Charfield6",
        ),
        migrations.RemoveField(
            model_name="center",
            name="Charfield7",
        ),
        migrations.RemoveField(
            model_name="center",
            name="Charfield8",
        ),
        migrations.RemoveField(
            model_name="center",
            name="Charfield9",
        ),
    ]
