# Generated by Django 4.1 on 2023-04-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0067_remove_center_charfield1_remove_center_charfield10"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Center_ID",
        ),
    ]
