# Generated by Django 4.1 on 2023-04-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0068_delete_center_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="center",
            old_name="Charfield2",
            new_name="Charfield02",
        ),
        migrations.RenameField(
            model_name="center",
            old_name="Charfield3",
            new_name="Charfield03",
        ),
        migrations.RenameField(
            model_name="center",
            old_name="Charfield4",
            new_name="Charfield04",
        ),
        migrations.RenameField(
            model_name="center",
            old_name="Charfield5",
            new_name="Charfield05",
        ),
        migrations.RenameField(
            model_name="center",
            old_name="Charfield6",
            new_name="Charfield06",
        ),
        migrations.RenameField(
            model_name="center",
            old_name="Charfield7",
            new_name="Charfield07",
        ),
        migrations.RenameField(
            model_name="center",
            old_name="Charfield8",
            new_name="Charfield08",
        ),
        migrations.RenameField(
            model_name="center",
            old_name="Charfield9",
            new_name="Charfield09",
        ),
    ]
