# Generated by Django 4.1 on 2023-04-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0069_rename_charfield2_center_charfield02_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="center",
            name="Charfield02",
        ),
        migrations.RemoveField(
            model_name="center",
            name="Charfield03",
        ),
        migrations.RemoveField(
            model_name="center",
            name="Charfield04",
        ),
        migrations.RemoveField(
            model_name="center",
            name="Charfield05",
        ),
        migrations.RemoveField(
            model_name="center",
            name="Charfield06",
        ),
        migrations.RemoveField(
            model_name="center",
            name="Charfield07",
        ),
        migrations.RemoveField(
            model_name="center",
            name="Charfield08",
        ),
        migrations.RemoveField(
            model_name="center",
            name="Charfield09",
        ),
    ]
