# Generated by Django 4.1 on 2023-04-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0070_remove_center_charfield02_remove_center_charfield03_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="Charfield02",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="center",
            name="Charfield03",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="center",
            name="Charfield04",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="center",
            name="Charfield05",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="center",
            name="Charfield06",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="center",
            name="Charfield07",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="center",
            name="Charfield08",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="center",
            name="Charfield09",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
