# Generated by Django 4.1 on 2023-04-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0071_center_charfield02_center_charfield03_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="commonfield",
        ),
    ]
