# Generated by Django 4.1 on 2023-04-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0072_delete_commonfield"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CreditBureauDetails",
        ),
        migrations.DeleteModel(
            name="CustomerRegistered",
        ),
        migrations.DeleteModel(
            name="ProductDetails",
        ),
        migrations.DeleteModel(
            name="RejectionReasonComments",
        ),
        migrations.DeleteModel(
            name="SharedServiceDetials",
        ),
    ]
