# Generated by Django 4.1 on 2023-04-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0073_delete_creditbureaudetails_delete_customerregistered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="Charfield1",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="center",
            name="Charfield10",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
