# Generated by Django 4.1 on 2023-04-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0074_center_charfield1_center_charfield10"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userrole",
            old_name="Charfield1",
            new_name="Charfield10",
        ),
        migrations.RenameField(
            model_name="userrole",
            old_name="Charfield2",
            new_name="Charfield20",
        ),
        migrations.RenameField(
            model_name="userrole",
            old_name="Charfield3",
            new_name="Charfield30",
        ),
        migrations.RenameField(
            model_name="userrole",
            old_name="Charfield4",
            new_name="Charfield40",
        ),
        migrations.RenameField(
            model_name="userrole",
            old_name="Charfield5",
            new_name="Charfield50",
        ),
        migrations.RenameField(
            model_name="userrole",
            old_name="Charfield6",
            new_name="Charfield60",
        ),
        migrations.RenameField(
            model_name="userrole",
            old_name="Charfield7",
            new_name="Charfield70",
        ),
        migrations.RenameField(
            model_name="userrole",
            old_name="Charfield8",
            new_name="Charfield80",
        ),
        migrations.RenameField(
            model_name="userrole",
            old_name="Charfield9",
            new_name="Charfield90",
        ),
    ]
