# Generated by Django 4.1 on 2023-04-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0075_rename_charfield1_userrole_charfield10_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="center",
            name="center_name",
            field=models.CharField(max_length=100),
        ),
    ]
