# Generated by Django 4.1 on 2023-05-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0077_alter_center_charfield1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="center",
            old_name="Charfield1",
            new_name="center_meeting_day",
        ),
    ]
