# Generated by Django 4.1 on 2023-05-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0078_rename_charfield1_center_center_meeting_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="Charfield10",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="Charfield20",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="Charfield30",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="Charfield40",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="Charfield50",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="Charfield60",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="Charfield70",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="Charfield80",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="Charfield90",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
