# Generated by Django 4.1 on 2023-05-01 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0081_alter_customerkyc_branchname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerkyc",
            name="BranchName",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="BranchName",
                to="LOAN.agent",
            ),
        ),
    ]
