# Generated by Django 4.1 on 2023-05-03 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0082_alter_customerkyc_branchname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approved_customer_kyc",
            name="BranchName",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Approved_BranchName",
                to="LOAN.agent",
            ),
        ),
    ]
