# Generated by Django 4.1 on 2023-05-03 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0083_alter_approved_customer_kyc_branchname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disbursement_customer_kyc",
            name="BranchName",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="disbursement_BranchName",
                to="LOAN.agent",
            ),
        ),
        migrations.AlterField(
            model_name="rejected_customer_kyc",
            name="BranchName",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rejected_BranchName",
                to="LOAN.agent",
            ),
        ),
    ]
