# Generated by Django 4.1 on 2023-05-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0084_alter_disbursement_customer_kyc_branchname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="center",
            name="center_meeting_day",
            field=models.DateField(null=True),
        ),
    ]
