# Generated by Django 4.1 on 2023-05-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0085_alter_center_center_meeting_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="center",
            name="center_Id",
            field=models.CharField(max_length=100),
        ),
    ]
