# Generated by Django 4.1 on 2023-05-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0087_userprofilerole_alter_userrole_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userrole",
            old_name="role",
            new_name="user_role",
        ),
    ]
