# Generated by Django 4.1 on 2023-05-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0088_rename_role_userrole_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrole",
            name="user_role",
        ),
    ]
