# Generated by Django 4.1 on 2023-05-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0089_remove_userrole_user_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="userRole",
        ),
    ]
