# Generated by Django 4.1 on 2023-05-09 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0092_remove_rejected_customer_kyc_disbursement_payment_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransactions",
            name="branchName",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="LOAN.branch"
            ),
        ),
    ]
