# Generated by Django 4.1 on 2023-05-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0093_banktransactions_branchname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banktransactions",
            name="AccountNumber",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
