# Generated by Django 4.1 on 2023-05-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0096_loan_application_details_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account_transaction",
            name="TransDate",
            field=models.DateTimeField(),
        ),
    ]
