# Generated by Django 4.1 on 2023-05-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0098_remove_loandetails_intfield3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loandetails",
            name="Number_of_months",
            field=models.IntegerField(null=True),
        ),
    ]
