# Generated by Django 4.1 on 2023-06-14 05:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("LOAN", "0100_alter_loandetails_activatestatus"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="userRole",
            new_name="userWithRole",
        ),
    ]
