# Generated by Django 4.1 on 2023-06-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0101_rename_userrole_userwithrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="userwithrole",
            name="agents_Name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
