# Generated by Django 4.1 on 2023-06-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0102_userwithrole_agents_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userwithrole",
            old_name="agents_Name",
            new_name="user_actual_Name",
        ),
    ]
