# Generated by Django 4.1 on 2023-06-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0103_rename_agents_name_userwithrole_user_actual_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approved_customer_kyc",
            name="BranchName",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Approved_BranchName",
                to="LOAN.userwithrole",
            ),
        ),
        migrations.AlterField(
            model_name="customerkyc",
            name="BranchName",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="BranchName",
                to="LOAN.userwithrole",
            ),
        ),
        migrations.AlterField(
            model_name="disbursement_customer_kyc",
            name="BranchName",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="disbursement_BranchName",
                to="LOAN.userwithrole",
            ),
        ),
        migrations.AlterField(
            model_name="rejected_customer_kyc",
            name="BranchName",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rejected_BranchName",
                to="LOAN.userwithrole",
            ),
        ),
    ]
