# Generated by Django 4.1 on 2023-07-08 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LOAN", "0104_alter_approved_customer_kyc_branchname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audittable",
            name="LoanId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="LOAN.loan_application_details",
            ),
        ),
        migrations.CreateModel(
            name="preClosedLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PreclosedDate", models.DateField()),
                ("PreclosedAmount", models.IntegerField()),
                ("TotalPreclosedEmi", models.IntegerField()),
                ("TotalEmi", models.IntegerField()),
                ("createdDate", models.DateTimeField()),
                ("updatedDate", models.DateTimeField(auto_now=True)),
                ("intfield1", models.IntegerField(null=True)),
                ("intfield2", models.IntegerField(null=True)),
                ("intfield3", models.IntegerField(null=True)),
                ("intfield4", models.IntegerField(null=True)),
                ("intfield5", models.IntegerField(null=True)),
                ("DateField1", models.DateTimeField(null=True)),
                ("DateField2", models.DateTimeField(null=True)),
                ("DateField3", models.DateTimeField(null=True)),
                ("DateField4", models.DateTimeField(null=True)),
                ("DateField5", models.DateTimeField(null=True)),
                ("Charfield1", models.CharField(max_length=50, null=True)),
                ("Charfield2", models.CharField(max_length=50, null=True)),
                ("Charfield3", models.CharField(max_length=50, null=True)),
                ("Charfield4", models.CharField(max_length=50, null=True)),
                ("Charfield5", models.CharField(max_length=50, null=True)),
                (
                    "LoanId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="LOAN.loan_application_details",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="loanemi",
            name="preClosedId",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="LOAN.preclosedloan",
            ),
        ),
    ]
