import datetime



AWS_ACCESS_KEY_ID = "AKIAT4YKK3J37RHGA35P"
AWS_SECRET_ACCESS_KEY = "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"
AWS_FILE_EXPIRE = 200
AWS_PRELOAD_METADATA = True
AWS_QUERYSTRING_AUTH = True
AWS_DEFAULT_ACL = None



DEFAULT_FILE_STORAGE = 'LMS.aws.utils.MediaRootS3BotoStorage'
STATICFILES_STORAGE = 'LMS.aws.utils.StaticRootS3BotoStorage'
AWS_STORAGE_BUCKET_NAME = 'dummylms'

AWS_S3_REGION_NAME = 'ap-south-1'
AWS_S3_SIGNATURE_VERSION = 's3v4'
